import { dirname, join } from 'node:path';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(scriptDir, '..');
const workspaceRoot = join(cliRoot, '..');
const outputPath = join(workspaceRoot, 'hub', 'src', 'web', 'embeddedAssets.generated.ts');
const contents = [
    '// This file is generated by cli/scripts/build-executable.ts when --with-web-assets is not used.',
    '// It intentionally contains no embedded assets.',
    '',
    'export interface EmbeddedWebAsset {',
    '    path: string;',
    '    sourcePath: string;',
    '    mimeType: string;',
    '}',
    '',
    'export const embeddedAssets: EmbeddedWebAsset[] = [];',
    ''
].join('\n');

writeFileSync(outputPath, contents, 'utf-8');
